version: '3.9'

services:
  ssh-key-manager:
    build: ./app
    container_name: ssh-key-manager
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./backups:/app/backups
    environment:
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_TO=${SMTP_TO}
      - DOMAIN=${DOMAIN}
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/startup.sh:/etc/nginx/startup.sh
    environment:
      - DOMAIN=${DOMAIN}
    entrypoint: ["/bin/bash", "-c", "/etc/nginx/startup.sh"]
    depends_on:
      - ssh-key-manager
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/html:/usr/share/nginx/html
      - ./certbot/startup.sh:/startup.sh  # <-- IMPORTANT new mount!
    entrypoint: ["/bin/sh", "/startup.sh"]
    environment:
      - DOMAIN=${DOMAIN}
      - SMTP_TO=${SMTP_TO}
    depends_on:
      - nginx
    restart: unless-stopped

volumes:
  sshkeys_data:
    driver: local